# permissions for end users to view petitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: petition-viewer-role
rules:
- apiGroups:
  - fdse.cloudnative
  resources:
  - petitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fdse.cloudnative
  resources:
  - petitions/status
  verbs:
  - get
