# permissions for end users to view petitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: petition-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: petition
    app.kubernetes.io/part-of: petition
    app.kubernetes.io/managed-by: kustomize
  name: petition-viewer-role
rules:
- apiGroups:
  - fdse.cloudnative
  resources:
  - petitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fdse.cloudnative
  resources:
  - petitions/status
  verbs:
  - get
